### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by teo-tsirpanis** [Kuinox/KuiLang#6]
The project doesn't have a license. It is a very good practice to have one.

**Comment by Kuinox** [comment]
Good question, there is no license because I'm indecisive on what to use.    
My current thoughts about it: 
I hope for this project to go far, but realistically it probably wont.  
The license is the hardest breaking change to make if you didn't prepared the terrain well enough.  
MIT & similar will cause the least friction to adoption.  
But, because of this, and the nature of this programming language if this get popular you could totally see some cloud company adding bunch of clever query rewriting rules written by people way smarter than me, and locking it behind their cloud.
Now their runtime is way more competitive than the open one and they benefit from the OSS works, for free.  

This is the same problem than elasticsearch/other and I want to avoid that.

**Comment by AsuMagic** [comment]
You don't need the same license for the entirety of the project FWIW. The compiler could be licensed in GPL, and the runtime to something more permissive. It would be good to figure out the answer to these questions:

- Should 3rd parties be able to ship a modified compiler without open-sourcing their changes?
- Should 3rd parties be able to modify the core libraries, the JIT, etc. without open-sourcing their changes? (Would the source compiler or parts of it be shipped in any way in the runtime?)

Something interesting to note - some libraries are GPL-licensed but have a linking exception, e.g. libstdc++, of which my understanding is that you must open source changes if you're shipping a modified version, but linking against the runtime does *not* require you to open source your application source code.

**Comment by teo-tsirpanis** [comment]
Resolved by #8.
